### ISSUE TITLE
The **BoundingBox** could not be found

### ISSUE THREAD

**Issue by LX-Linxi** [trungvdhp/mpsnet#1]
The **BoundingBox** structure definition could not be found in palmlib.cpp and palmlib.h

**Comment by trungvdhp** [comment]
We have fixed this issue: in palmlib.h file, the **Landmarks** structure has been modified into the **BoundingBox** structure

**Comment by HSY-hsy-HSY** [comment]
Thank you very much for your prompt answer to my question. 
I am a beginner of c and not very familiar with it. I found some other problems when running the code. I would appreciate it if you could help me with them:

1. undeclared identifier error (C2065) on those names: t3(lines528,1344), edge_begin(line582,609), edge_end(line581,608), binaryImage(line1292,)
2. "scale" is not a member of "Landmarks" (C2039)in line 1467.

**Comment by LX-Linxi** [comment]
> We have fixed this issue: in palmlib.h file, the **Landmarks** structure has been modified into the **BoundingBox** structure

Thank you very much for your prompt answer to my question.
I am a beginner of c and not very familiar with it. I found some other problems when running the code. I would appreciate it if you could help me with them:

undeclared identifier error (C2065) on those names: t3(lines528,1344), edge_begin(line582,609), edge_end(line581,608), binaryImage(line1292,)
"scale" is not a member of "Landmarks" (C2039)in line 1467.

**Comment by trungvdhp** [comment]
Thank you for your detection. In our cleaning code process, we have lost some definitions. We have updated them in palmlib.h and palmlib.cpp files.

**Comment by LX-Linxi** [comment]
> Thank you for your detection. In our cleaning code process, we have lost some definitions. We have updated them in palmlib.h and palmlib.cpp files.

I read your article Recognizing Palm Vein in Smartphones Using RGB Images. I am not really understand how to crop such a piece to a 160 * 160 palm center area [Algorithm 2: Extracting palm vein ROI: 1) crop to the center square image Ic and scale down to smaller image Is (160 × 160 pixels)]. 
Does this have anything to do with the frame(line1270)? At first I changed the frame to rgbImage, but I find this is not correct. 
Could you add the definition of **frame(line1270)**?

**Comment by trungvdhp** [comment]
We have changed **frame** to **rgbImage**. Please see example [croppedImage](https://github.com/trungvdhp/mpsnet/blob/main/Images/crop_center_square.png)
