### ISSUE TITLE
function 'extractPalmROI' Exception: vector subscript out of range

### ISSUE THREAD

**Issue by HeloWong** [trungvdhp/mpsnet#3]
When read image 'ntust_ip_s1.png', and use function **extractPalmROI** to extract ROI,  Debug Assertion Failed, and error message is: "vector subscript out of range"
here is my example code:

```cpp
Mat rgbImage = imread(image_path, cv::IMREAD_COLOR);
Mat roiImage;
int roiSize = 128;
try {
    extractPalmROI(rgbImage, roiImage, roiSize);
} catch (const std::exception& ex) {
    std::cerr << std::endl << "Exception occurred: " << ex.what() << std::endl << std::flush;
    return EXIT_FAILURE;
}
```

could you give any advice? I would be grateful for your help.

**Comment by trungvdhp** [comment]
Note that the **imread** function will return the BGR image, not the RGB image; please use **cvtColor** to convert the BGR image into the RGB image first. 
We have updated **palmlib.cpp** and **palmlib.h**. A **main** function was added to illustrate.
Here are the output images: [CroppedImage](https://github.com/trungvdhp/mpsnet/blob/main/Images/ntust_ip_s1_crop.png), [BinaryImage](https://github.com/trungvdhp/mpsnet/blob/main/Images/ntust_ip_s1_binary.png), [ROI](https://github.com/trungvdhp/mpsnet/blob/main/Images/ntust_ip_s1_roi.png)

**Comment by HeloWong** [comment]
Ok, I get it now, thanks
